config/routes.rb
Rails.application.routes.draw do

  resources :books

  devise_for :users , controllers: { registrations: "registrations" }
  root 'page#home'

   get 'dashboard' => 'page#dashboard'

   post '/buy/:slug', to: 'transactions#create', as: :buy
   get '/pickup/:guid', to: 'transactions#pickup', as: :pickup


    resources :subscribers




end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

        user ||= User.new
        
        can :read, :all
        can :manage, Book do |book|
           book.try(:user) == user
        end







    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/book.rb
class Book < ActiveRecord::Base

     extend FriendlyId
     friendly_id :title, use: :slugged

     belongs_to :user
     has_many :sales

     has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "no_image.png"
     validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  has_attached_file :resource, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "no_image.png"
#     validates_attachment_content_type :resource, :content_type => /\Aimage\/.*\Z/

    validates_attachment_content_type :resource, content_type: { content_type: "application/pdf" }


  validates_numericality_of :price, greater_than: 49, message: "Must be at least 50c"


end

app/models/sale.rb
class Sale < ActiveRecord::Base
  
    before_action :populate_guid
    belongs_to :book
 
       include AASM

       aasm column: 'state' do
           state :pending, initial: true
           state :processing
           state :finished 
           state :errored

           event :process, after: :charge_card do
                transitions from: :pending, to: :processing
           end

           event :finish do
               transitions from: :processing, to: :finished
           end

           event :fail do
                transitions from: :processing, to: :errored
           end           

       end


        def charge_card
            begin
                save!
                charge = Stripe::Charge.create(
                    amount: self.amount,
                    currency: "usd",
                    card: self.stripe_token,
                    description: "Book Sale")
                self.update(stripe_id: charge_id)
                self.finished!
                rescue Stripe::Error => e
                self.update_attributes(error: e.message)
                self.fail!
                end
        end

       

    private
    def populate_guid
        self.guid = SecureRandom.uuid()
    end

    



end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    has_many :books


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

    rescue_from CanCan::AccessDenied do |exception|
        redirect_to root_path , notice: "Voce nao está autorizado a esta area"
    end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  

    before_action :set_book, only: [:show, :edit, :update, :destroy]


  # GET /books
  # GET /books.json
  def index
    @books = Book.where(avaliable: true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = current_user.books.new
  end

  # GET /books/1/edit
  def edit
      authorize! :manage, @book
  end

  # POST /books
  # POST /books.json
  def create

    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
      authorize! :manage, @book
      
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
      authorize! :manage, @book
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :description, :price, :avaliable, :user_id, :image, :resource)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
    
  def home
      @books = Book.last(3)
  end
    
  def dashboard
    @books = current_user.books
#    @purchases = Sale.where(buyer_email: current_user.email)
 #   @sales = Sale.where(seller_email: current_user.email)
  end




end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistationsController
    
    protected

    def after_sign_up_path_for(resource)
        '/subscribers/new'
    end



end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
    before_action :authenticate_user!

    def new
    end

    def update
        token = params[:stripeToken]
        customer = Stripe::Customer.create(
            card: token,
            plan: 1020,
            email: current_user.email
        )
        current_user.subscribed = true
        current_user.stripeid = customer.id
        current_user.save
        redirect_to books_path
    end





end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

   def create
       book = Book.find_by!(slug: params[:slug])
       sale = book.sales.create(
           amount = book.price,
           buyer_email = current_user.email,
           seller_email = book.user.email,
           stripe_token: params[:stripeToken])


       sale.process!
       if sale.finished?
           redirect_to pickup_url(guid: sale.guid),notice: "Ok payment done"
       else
           redirect_to book_path(book), notice: "Something get wrong..."
       end


   end







   def pickup
       @sale = Sale.find_by!(guid: params[:guid])
       @book = @sale.book
   end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/books/_book.html.erb
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <%= link_to book_path(book) do %>
    <%= image_tag book.image(:original), class: "img-responsive" %>
        <% end %>
      <div class="caption">
          <h3><%= book.title %></h3>
          <p><%= book.title %></p>
          <h3>US$ <%= book.price.to_f / 100 %></h3>



      </div>
    </div>
  </div>

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>


  <div class="col-md-6 col-md-offset-3">
      <div class="well">
          <%= f.input :title, label: false, placeholder: "Name", input_html: { class: "form-control" }  %>
    <%= f.input :author ,label: false, placeholder: "Author"%>
    <%= f.input :description ,label: false, placeholder: "Description" %>
    <%= f.input :price , label: false , placeholder: "Price US$" %>
    <%= f.check_box :avaliable %> Avaliable
    <br>
    <h3>Imagem</h3>
    <%= f.file_field :image %>
    <h3>Anexo</h3>
    <%= f.file_field :resource %>
    <br>
    <%= f.button :submit, class: "btn btn-primary btn-block" %>
<% end %>
  
<%= link_to 'Back', books_path %>
 
       </div>
  </div>

app/views/books/edit.html.erb
<h1 align="center">Editing Book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<h1>Livros Disponiveis</h1>
<%= link_to 'New Book', new_book_path , class: "btn btn-primary" %>

<hr>
<%= render @books %>

app/views/books/new.html.erb
<h1 class="text-center">New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="row">
<div class="col-md-4">
    <%= image_tag @book.resource.url(:medium), class: "img-responsive" %>
</div>
<div class="col-md-6 col-md-offset-2" align="center">
    <div class="well center">
    <h1>
  <%= @book.title %>
  <hr>
    </h1>
    <h3>
  <%= @book.author %>
  </h3>
  <p>
  <%= @book.description %>
  </p>
  <h1>
      US$
  <%= @book.price.to_f / 100 %>
</h1>
<p>Avaliable? 
  <%= @book.avaliable %>
  </p>
  <p>
  <%= @book.user.email %>
  </p>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %> | 
<%= link_to 'Destroy' , book_path(@book), method: :delete, data: { confirm: "Vc tem certeza?" } %>


<%= form_tag buy_path(slug: @book.slug) do %>
    <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-name="BK Bookstore"
    data-description="<%= @book.title %>"
    data-amount="<%= @book.price %>"
    data-email="<%= current_user.email %>"
    >
</script>
<% end %>

</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a>
        <%= link_to 'Bookstore', root_path , class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
          <li>
            <%= link_to 'Dashboard', dashboard_path  %>
            </li>
          <li>
            <%= link_to 'Books', books_path %>
          </li>

          <li>
          <%= link_to 'Conta', edit_user_registration_path  %>
          </li>
          <li>
            <%= link_to 'Log Out', destroy_user_session_path , method: :delete  %>
            </li>
        <% else %>
            <li>
            <%= link_to 'Cadastrar', new_user_registration_path  %>
            </li>
            <li>
            <%= link_to 'Log In', new_user_session_path  %>
            </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
    <% flash.each do |type, message| %>
      
<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <strong><%= message %></strong>
</div> 
        
    <% end %>
<%= yield %>


</div>
</body>
</html>

app/views/page/dashboard.html.erb
<div class="row">

    <div class="col-md-4">
        <h1 align="center">Dashboard</h1>
        <h3>My Books | <%= link_to 'New Book', new_book_path, class: "btn btn-info btn-sm" %></h3>
    <div class="table table-condensed">
        <div class="bs-example" data-example-id="condensed-table">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Avaliable</th>
          <th></th> 
        </tr>
      </thead>
      <tbody>
        <%= render 'books' %>
      </tbody>
    </table>
  </div>
    </div>
    </div>

 <div class="col-md-4">
        <h1 align="center">Purchases</h1>
        <h3>My Books | <%= link_to 'New Book', new_book_path, class: "btn btn-info btn-sm" %></h3>
    <div class="table table-condensed">
        <div class="bs-example" data-example-id="condensed-table">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Avaliable</th>
          <th></th> 
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
    </div>
    </div>
 <div class="col-md-4">
        <h1 align="center">My Sales</h1>
    <div class="table table-condensed">
        <div class="bs-example" data-example-id="condensed-table">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Avaliable</th>
          <th>Buyer</th> 
        </tr>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
    </div>
    </div>


























</div>

app/views/page/home.html.erb
<h1>Bem vindo a BK  Bookstore</h1>

<%= render @books %>

app/views/subscribers/new.html.erb
<h1>Nova Assinatura</h1>
<%= render 'form' %>

app/views/transactions/pickup.html.erb
<h1>Obrigado pela sua compra</h1>
<%= @sale.guid %>
<p>Aqui esta o link do seu novo livro</p>

<%= link_to 'Download', @book.resource.url %>